### PR TITLE
Improve performance of It.Is matcher when used with an expression by compiling only once

### PR DESCRIPTION
**Pull request by peterder72**

### CODE REVIEW

**Comment by peterder72** [comment]
Forgot to update the changelog, will do

**Comment by kzu** [comment]
No need. The changelog is generated from the PRs/Issues associated once merged, at the time of release.

**Comment by kzu** [comment]
You can just remove the commit to the changelog and then I'll merge it.

**Comment by peterder72** [comment]
Done! It would also be a good idea to update the Contributing.md manual, seeing that the procedure is different now. But in a separate PR

**Comment by kzu** [comment]
I think you actually need to rebase on top of main and just skip the commit to the changelog: 

image

**Comment by peterder72** [comment]
Rebased, fixed now

**Pull request merged**
